withastro/astro.build

- src/components/landing/Grid.astro
Firefox really chokes on the background grid animation, possibly related to [this](https://bugzilla.mozilla.org/show_bug.cgi?id=739176) older Gecko issue
Let's just disable the animation in Firefox, I'd hate to change the design here - the transforms and blur filters don't seem to be a problem without the animation
> Disabling the hero background grid animation for Firefox

- astro.config.ts
- package-lock.json
- package.json
- src/components/blog/Card.astro
- src/components/landing/Performance.astro
- src/pages/index.astro
- upgrades to astro@0.23
- upgrades `astro-icon` to support 0.23 and static builds
- uses `set:html` for all unescaped text (that build warning was a huge win 🥇)
> Upgrading to astro 0.23

- public/_redirects
Adds shortlink for https://astro.build/config
This will be paired with https://github.com/withastro/astro/pull/2803 to make finding the Astro configuration reference much easier.
> Add `/config` shortlink

- public/_redirects
[Related PR](https://github.com/withastro/astro/pull/2856) using the redirect for `Astro.resolve()` deprecation warnings
> Adding redirect for Astro.resolve() migration docs

- src/components/showcase/ShowcaseCard.astro
As discussed on Discord [in #general](https://ptb.discord.com/channels/830184174198718474/830184175176122389/962105868516741163) it would be nice to give Astro credit where credit is due and show when traffic comes from Astro! Right now traffic to the pages in the showcase list looks like "Direct traffic" in analytics tools.
I looked around and couldn't find any implications for this, but I'm happy to reconsider if this is here for a reason.
Fun fact: we could also technically remove `noopener` since all links with `target="_blank"` automatically gets `rel="noopener"`, but it's probably best to keep it in case we ever want to remove `target="_blank"`.
> Remove `noreferrer`

- src/pages/blog/introducing-astro.md
fix a little image extension mismatch in "the introducing astro" blog post 🚀
> fix: hero image extension missmatch in "introducing astro" blog post

- src/components/landing/Integrations.astro
Need to track down why this broke after beta.51, but nesting `map()` calls in JSX is no longer rendering properly
> hotfix: JSX stopped supporting nested maps?

- src/components/Aside.astro
- src/components/FlyoutMenu.astro
- src/components/Footer.astro
- src/components/Nav.astro
- src/components/PillList.astro
- src/components/PixelLink.astro
- src/components/blocks/CardsBlock.astro
- src/components/integrations/IntegrationCard.astro
- src/components/landing/Community.astro
- src/components/landing/Demo.astro
- src/components/landing/DemoIllustration.astro
- src/components/landing/Hero.astro
- src/components/landing/Integrations.astro
- src/components/landing/Performance.astro
- src/components/landing/Sponsors.astro
- src/components/landing/Title.astro
- src/components/landing/Trusted.astro
- src/components/showcase/ShowcaseCard.astro
- src/components/themes/ThemeCard.astro
- src/config.ts
- src/layouts/Catalog.astro
- src/pages/blog/index.astro
- src/pages/index.astro
- src/pages/integrations/[slug].astro
- src/pages/integrations/index.astro
- src/pages/themes/[slug].astro
- src/pages/themes/index.astro
I audited `astro.build` with the same test suite used in the docs repo:
- Screen reader navigation using NVDA (Duplicate/missing announcements, unclear or unnecessary landmarks, non-descriptive text, etc).
- Keyboard-only navigation.
- Mobile navigation with/without screen reader and keyboard-only.
- High Contrast/Forced Colors mode (Elements boundaries visibility, unclear active elements, styling conflicts, etc).
- HTML/ARIA semantics.
- Color contrast.
Per-commit, additional comments to clarify decisions and reasons (plus images!):
[Add custom search placeholder prop](https://github.com/withastro/astro.build/commit/57d54e467cd5a14338934da8e0d302f3364db957)
Placeholder text needs to be descriptive and not only use the same label as the input name/type as a way to add more clarity and …
> Accessibility Improvements

- public/_redirects
Existing links for Code of Conduct and Governance result in `404` since these files have been moved to the organization community health files location: https://github.com/withastro/.github.
> Update Code of Conduct and Governance urls

- src/components/Header.astro
Closes #323 
Issue: For a small range of screen widths, the hamburger menu opens the nav bar horizontally, but also overlaps with the first menu item. 
Changing the Tailwind class from `-mr-2` to `mr-2` fixes the hamburger overlap, but when the item is focused, the outline still touches the first nav menu item: (Good enough, though, when no focus is visible.)
This PR changes the Tailwind class to `mr-3` which shifts the entire hamburger and its outline far enough so as not to interfere with the menu items, but when closed, is maybe a little too large for what you'd ideally want?
Anyway, do with this what you will!
> Tailwind right margin class affecting nav

- src/components/CardGrid.astro
Only `li` elements can be children of `ul`. This removes an errant `footer` element.
> Fix failing AXE error

- .github/workflows/nightly.yml
- scripts/integrations.json
- scripts/integrations.mjs
- scripts/update-integrations.mjs
`@astrojs/og` is super experimental and we probably don't want to publicize it yet
Also updates variable names to more inclusive `allowlist` and `blocklist`
> Add `@astrojs/og` to blocklist

- src/components/content-examples/API.astro
If someone were to try this code snippet for themselves after November 28, 2022, they might be disappointed because it wouldn't work. Therefore it is necessary to update the URL to a new version made by the author which will continue to work after November 28, 2022.
> fix: use updated Wow URL in API content example

- public/_redirects
closes #373
The [Astro Playground](https://astro.build/play) is a little outdated and really won't match more full-featured tools like StackBlitz
This effectively deprecates our playground by redirecting to [astro.new](https://astro.new) where multiple different browser-based editors can be used to try out Astro
> Redirecting astro.build/play to astro.new

- src/pages/on/[platform].astro
Adds `/on/[platform]` social links as client-side redirects.
Allows our Mastodon social links to all be verified and users to find us more easily!
> Add /on links for socials

- src/components/Header.astro
- src/data/site.ts
- src/types.ts
Follow-up to #453, includes Mastodon in the site footer but not the main navigation header
> remove mastodon from main header nav

- src/types.ts
Fixes the Mastodon logo still showing in the header as per https://github.com/withastro/astro.build/pull/455#issuecomment-1347753267
The schema didn’t include the `footerOnly` property needed to filter out the Mastodon icon in the header, so it was getting dropped when parsing.
Zod ships a `z.infer<>` generic to make it easy to get a type that exactly matches a schema. I’ve used this to replace the manual duplication required to maintain both a TS interface and Zod schema. Should help prevent similar issues in the future where we might update the type but forget to update the schema.
> Fix missing fields in schema

- src/utils/discord.ts
This probably also applies to theme submissions. The issue was the use of `Headers`, which exists in Node 18, but not the lambda's node 14
Might also be a good idea to update to 18
> Fix error on showcase submit

- public/_redirects
We had been using a temporary URL while waiting on Figma to approve the community submission, it's now live 🚀
> Updates the figma redirect with the final Community URL

- netlify/functions/submit-showcase/index.ts
Currently the Netlify function for Showcase submissions redirects to the theme success page.
> Redirect to correct link on showcase submit

- src/pages/showcase/submit.astro
- src/pages/themes/submit/index.astro
- src/utils/formSize.ts
Netlify Functions limits requests to [6MB max](https://docs.netlify.com/functions/overview/#default-deployment-options)
[x] updates the submission forms to show 6MB as the max
[x] adds a basic FormData size calculation to alert users when images are too large **before** hitting Netlify (where the function just fails)
[x] logs a custom event to Fathom so we can track how often the file limit is hit
> Adds a validation step for theme/showcase submission file size limits

- src/components/Hero.astro
- src/components/Starfield.astro
Lighthouse showed an accessibility issue with the background to text contrast ratio on a specific element. The issue didn't really exist, because the `Starfield` component floats behind, applying a gradient with a dark enough color not to cause any issues. Lighthouse can't detect this, so we give a "fallback" background to the header which exists behind the `Starfield` component. 
TLDR: The end result is the same, but the single accessibility issue on the homepage is fixed
> Fix invisible a11y issue in lighthouse

- src/components/BaseHead.astro
- src/pages/404.astro
I noticed that all 404 events in Fathom are being reported as for the `/404/` path rather than a useful path like we get for docs. My guess is that this because we don’t set a canonical URL for 404 pages in docs but this is set for astro.build.
This PR sets the canonical URL to `null` on the 404 page. The SEO component we’re using still emits the canonical tag but with the value an empty string, so we need to test if Fathom will ignore that as I would hope.
> Fix 404 monitoring

- src/components/Button.astro
- src/pages/themes/details/[slug].astro
Adds two separate events when visitors click on "Get Started" or "Live Demo" for a theme
Note that these events still fall under Fathom's terms of service and match our existing privacy-focused data policy
> adds Fathom events to theme details CTAs

- src/data/showcase/the-guardian-engineering.json
Previously, the link to The Guardian Engineering led to a `Page Not Found` page: https://theguardian.engineering/open-source/. Removing the trailing slash fixes the issue: https://theguardian.engineering/open-source
> Fix link to The Guardian Engineering site

- astro.config.mjs
This updates the `astro.config.mjs` file to prioritize Netlify preview URLs for the main `site` config
In non-production deployments, the Netlify preview URL will be used as the root domain, in production or when Netlify env variables are undefined `https://astro.build` will be used
> Testing netlify's deploy URL env flag

- src/utils/discord.ts
`import * as z from 'astro/zod'` is not valid at runtime at the moment
> fix zod import

- scripts/npm.mjs
- src/data/integrations.json
Currently on the integrations page for adapters there are 4 instances of cloudflare adapters (astro-cloudflare, astro-cloudflare-node, astro-js-cloudflare), all linking to the main repo and they should probably removed in favour of the `@astrojs/cloudflare` package.
> Remove redundant entries for @astrojs/cloudflare adapter

- netlify/functions/submit-showcase/index.ts
- netlify/functions/submit-theme/index.ts
Some submissions were getting through without being stopped by browser HTML validation. Added a new backend check for images to prevent this
> validate submission images on backend

- public/_redirects
- src/components/Footer.astro
- Add a `/partnerships` redirect to Notion
- Add this link to the site footer:
> Add partnerships link

- src/components/ThemeCard.astro
- src/pages/themes/details/[slug].astro
- src/types.ts
For themes with public repos (all free themes), a Deploy to Netlify button is included on the theme details page in additions to our Get Started & Live Demo links
> feat: adds Deploy to Netlify buttons for free themes

- src/components/Hero.astro
- src/components/PageTitle.astro
Applies the same fix as d641e62 to pages beyond the home page.
> Stop incorrect color contrast error being reported

- src/components/forms/ImageInput.tsx
- src/components/forms/TagInput.tsx
- src/pages/themes/details/[slug].astro
- Add explicit true value to `aria-hidden` where missing
- Fix color contrast of links on [theme pages](https://deploy-preview-545--astro-www-2.netlify.app/themes/details/portfolio/)
| Before | After |
|---|---|
| <img width="174" alt="image" src="https://user-images.githubusercontent.com/357379/220596621-923ccf28-1e29-4cca-ad11-0700b90ebac8.png"> | <img width="177" alt="image" src="https://user-images.githubusercontent.com/357379/220596653-bb6541cc-d673-4aaf-baca-98f6a5aa05db.png"> |
Also noticing that the Quill editor we’re using for the theme submission form is missing accessible labelling for its toolbar. There’s been [an open PR to fix that on their end](https://github.com/quilljs/quill/pull/3639) for nearly 6 months but seems maybe they’re not interested. Might be good to …
> a11y fixes

- src/pages/privacy.mdx
Adds a brief mention that we use Feedback Fish to collect docs feedback.
> Mention Feedback Fish in privacy policy

- src/components/Header.astro
- src/components/HeaderDrawerContent.astro
- src/helpers/disclosure.ts
- src/layouts/MainLayout.astro
[x] blocks page scrolling when the menu is open
[x] allows the mobile menu to scroll vertically
[x] automatically closes the menu when the window is resized past 1024px
> fix: :bug: page content can be scrolled with the mobile menu open

- src/layouts/MainLayout.astro
Showcase page has responsive issues with mobile view because of the background image overflowing on the x-axis. I fixed it with this merge request by adding hiding the overflow on the x-axis.
fix: #569
Before
After
> fix: showcase page mobile view overflow

- src/styles/fonts.css
- tailwind.config.cjs
This configures manually adjusted fallback font definitions using common system fonts to help reduce CLS in browsers that support it. `size-adjust` doesn’t have amazing [browser support](https://caniuse.com/mdn-css_at-rules_font-face_size-adjust) just yet, but it’s a safe progressive enhancement that benefits people who are using those browsers.
I used this handy comparison tool to tweak these values: https://screenspan.net/fallback
https://user-images.githubusercontent.com/357379/223765055-982698b4-0a58-4ca9-97b2-067f812fda1d.mp4
https://user-images.githubusercontent.com/357379/223765644-ffc8d11c-bb90-439e-af23-b234637fe4a5.mp4
> Configure size-adjusted fallback fonts to reduce CLS

- src/components/NotificationBanner.astro
- tailwind.config.cjs
- Adds an accessible label reading “Hide Banner” to the X icon button in the notification banner
- Tweaks the colour contrast which was technically failing WCAG AA contrast requirements. New version on the left, old version on the right:
(The gradient change is equivalent to changing lightness in the HLS colour from 63% to 60%)
> Notification banner a11y fixes

- src/helpers/disclosure.ts
In the mobile menu, if you click on the Resources dropdown then try to close the menu both elements end up handling the event and call `setVisible(!visible())` twice, flipping it to closed and then back open immediately
This updates the focus-lost handler to ignore the even if the mobile menu button is the new focus target
> :bug: Fixes a click handler loop in the mobile menu

- src/components/CatalogSubmitCallout.astro
- src/components/SearchFilter.astro
- src/pages/integrations/[...page].astro
- src/pages/themes/[...page].astro
Reworks the integrations and themes catalogue hierarchy so that there is a logical progression of heading levels.
> Ensure headings are in a sequentially descending order

- src/pages/404.astro
- src/pages/_components/ContentFirstFast.astro
- src/pages/_components/FullSpeedAhead.astro
- Add underline to links in homepage sections
- Add `href` to homepage and 404 page links that were missing
> Link fixes

- src/pages/_components/ContentFirstFast.astro
Using `client:idle` here so the JS request and hydration doesn't trigger while the page is scrolling
This is a pretty minor perf difference, but while profiling scrolling on older android devices I noticed this `client:visible` hydration was occasionally making a big enough hit here to drop a couple frames during scroll
> allowing the browser to load the ExampleShowcase component on idle

- src/components/HeaderNav.astro
- src/components/SkipLink.astro
- src/layouts/MainLayout.astro
Adds a "Skip to content" link!
Note: 
- Couldn't find a good way to vertically align with the navbar, it would depend on some calculations that would not work depending on if the notification bar is visible or not.
- Base white button used custom gradient/background styles that were incompatible with transform/drop-shadow for some reason a Tailwind noob can't understand, therefore I "forked" them. Also, removed the transition to avoid a super animated skip link, removing `transition: none` brings it back if we want.
> Add skip to content link

- src/pages/press/index.astro
Fixing a crazy style bug when linking to `/press/#assets` in the best way possible, deleting the offending background glow!
I couldn't actually tell why this bug exists, but when deep linking to the `#assets` ID the page wrapper seems to not have the `position: relative` style actually applied, preventing the bottom glow from using absolute positioning to crop off
It feels a lot like a corner case rendering bug where the browser would have needed to make an extra pass on the render tree to update positioning.  Can't confirm that though, best I can tell the `relative` style is applied in devtools **and** toggling it on/off in place fixes the bug.  It really is just not being accounted for at render time for some reason :shrug:
> fix: scroll on the Press page deep link

- src/pages/showcase/[...page].astro
- src/pages/showcase/_components/SubmitSite.astro
- Adds `alt=""` to mark Houston as decorative
- Wraps the submit component in `<li>` as it’s inside `<ul>`.
Not sure if there‘s a better way given I think the intent was for this `<aside>` to be outside of the list flow. Maybe if the `<ul>` had `display: contents`, the `<aside>` could follow `<ul>` and the `<aside>` and all the `<li>`s follow the grid of a wrapper component? But I seem to remember `display: contents` messing up list item ARIA role maybe? So went with this simple solution — NWTWWHB!
> Fix a11y in showcase submit component

- public/_redirects
Closes https://github.com/withastro/astro/pull/6543
https://astro.build/issues/compiler return a 404 page.
> Add /issues/compiler redirect

- public/_redirects
- src/components/BaseHead.astro
- src/components/Footer.astro
- src/components/SEO.astro
- src/pages/404.astro
- src/pages/themes/submit/_components/BestPractices.astro
Pulling back over a couple vanity URLs that we weren't using but were supported in the previous site
This also updates the 404 page to make sure it never includes a canonical URL
> Adding back a few vanity redirects and fixing 404 canonical

- src/pages/themes/submit/index.astro
- src/process-env.ts
This moves the check for `DISCORD_` environment variables to a runtime check when the form is submitted
Netlify PR preview builds from community members won't include private environment variables, breaking the build immediately
> fix: lazy validate env variables in the theme submit route

- src/content/integrations/accessible-astro-components.md
Was just randomly browsing the integrations and found that they changed the URL.
> Fix: accessible-astro-components URL change

- .github/workflows/weekly.yaml
This PR updates the [create-pull-request GH action](https://github.com/peter-evans/create-pull-request) to latest just in case that’s the source of our troubles. No major changes in v4 per [their changelog](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md).
> Update `peter-evans/create-pull-request` to v4

- src/content/blog/astro-210.mdx
The double dash `--watch` was getting converted to an em-dash. ~~Putting a zero-width space between them breaks that up and~~ Wrapping in backticks makes the switch appear ~~(at least visually)~~ as two dashes.
Before:
After:
> Use backticks to preserve CLI flag double-hyphen

- scripts/update-showcase.mjs
This PR adds an additional URL to the list of origins disallowed in the showcase update script.
> Add camo.githubusercontent.com to showcase script block list

- src/content/blog/astro-250.mdx
Link typo to client directives docs
> Fix link typo in 2.5 blog post

- scripts/update-showcase.mjs
Escape the `after` query parameter in the graphql query that fetches discussion comments in the showcase script. We just hit a case where the value contains `=` and that is causing errors. This wraps the value in quotes to avoid that.
Triggered a run from this branch here: https://github.com/withastro/astro.build/actions/runs/5112550826/jobs/9190722693
Seems to be working as expected.
> Fix update-showcase script

- src/styles/prose.css
Increasing our prose font size from 16px to 18px on screens above 1024px wide
> Bumping blog font size to 18px on large screens

- src/pages/themes/details/[slug].astro
In themes with only one image, the detail page should always show the image at 16:9 aspect ratio.
**Before** https://astro.build/themes/details/art-portfolio/ 
**After** https://deploy-preview-714--astro-www-2.netlify.app/themes/details/art-portfolio/
> Using 16:9 aspect ratio for theme images

- src/pages/_components/CoreWebVitalsGraphItem.astro
The old version weights the scores such that the performance of non-Astro frameworks is understated. Change rebases this scale to 0 which does generate a bit of "dead space" but more accurately shows the relative difference between the scores.
> Fix misleading score transformation

- tailwind.config.cjs
Inter Variable is currently not being utilized due to a space missing in the font-family name.
@font-face declarations: https://astro.build/_astro/404.2624b2aa.css
Fixes Inter Variable not being used, which is shipped, but currently not being utilized.
https://astro.build/_astro/inter-latin-wght-normal.450f3ba4.woff2
---
[Video Showing Before and After](https://github.com/withastro/astro.build/assets/20273871/ac1a3279-fb0a-467f-b25c-1fe6917e5167)
> Fix: Use the font-family name defined in @font-face declaration Inter Variable

- astro.config.mjs
Our open graph images need to use the preview URLs when building so that we can test the social share cards
> Adding logic to use Vercel env variables for preview "site" config

- src/components/Footer.astro
- src/content/pages/telemetry.md
This adds a page detailing what telemetry data is collected, why it's collected, how it may be used, and how to opt-out.
Astro's CLI collects anonymous telemetry data that is used internally to help uncover issues and prioritize features that will have the most impact on Astro users.  None of the data that we collect is personally identifiable. It has never and will never be sold or monetized in any form.
> Adding telemetry disclosure and documentation

- astro.config.mjs
- vercel.json
This adds the `trialingSlash` config in `vercel.json` and updates our redirects to expect a trailing slash
ex: this should handle redirecting both `astro.build/chat` and `astro.build/chat/`
Redirects tested to confirm:
https://astro-build-git-redirects-trailing-slash-astrodotbuild.vercel.app/chat
https://astro-build-git-redirects-trailing-slash-astrodotbuild.vercel.app/chat/
https://astro-build-git-redirects-trailing-slash-astrodotbuild.vercel.app/releases/3.0.0-rc.9
https://astro-build-git-redirects-trailing-slash-astrodotbuild.vercel.app/releases/3.0.0-rc.9/
> redirects should handle trailing slashes

- .github/workflows/weekly.yaml
Our weekly CI depended on the `format` package script which we removed in #804.
This PR updates the workflow to use `lint:prettier` instead, which should be the only formatter relevant given these tasks generate `.md` and `.webp` files exclusively.
> Update weekly CI to run new formatter command

- vercel.json
Looks like this was lost during the Vercel migration
> Adding back the /examples redirect

- src/components/BaseHead.astro
- src/components/SEO.astro
Fix an issue with the trailing slash being added after query params.
Previous:
```
https://astro.build/themes/2/?categories%5B%5D=portfolio/
```
Now:
```
https://astro.build/themes/2/?categories%5B%5D=portfolio
```
> Fix canonical trailing slash with query params

- package.json
- pnpm-lock.yaml
A security vulnerability was [reported](https://github.com/advisories/GHSA-m95q-7qp3-xv42) in zod <= 3.22.2 and a patch was published in zod 3.22.3
This upgrades zod to @latest to resolve the dependency vulnerability
> chore(deps): Update zod to @latest

- vercel.json
https://astro.build/docs gave a sad and cryptic 404:
Now it'll redirect users to https://docs.astro.build ⏩
> feat: Add docs redirect

- src/content/blog/experimental-static-build.mdx
I've seen quite a few people asking about this blog post! It has fairly good SEO so people land here often. This feature flag was needed for a version of Astro prior to v1.0.0.
We might want to think of a way to automate this, but a manual `Note` inclusion seems fine for now.
> Add note about outdated `--experimental-static-build`

- scripts/update-showcase.mjs
This week’s CI script updating the showcase failed trying to parse an invalid URL: https://github.com/withastro/astro.build/actions/runs/6770471354/job/18411300157
Not 100% sure which link we’re scraping that is tripping it up (we just get `#`), but this PR adds some error handling so the script can keep running, ignoring any invalid URLs like this.
> Handle update-showcase script error

- src/content/themes/ev0.md
Original theme developer has changed the demo url on the repo.
https://github.com/gndx/ev0-astro-theme
Current demo link is broken.
> fixes ev0 theme broken demo link

- src/components/Footer.astro
Renames the "Community" category to "Ecosystem" and add community as a link to community.astro.build
> chore: rename community to ecosystem

- scripts/update-showcase.mjs
- Blocks a (new?) GitHub images origin so that images people add to the GitHub discussion are ignored
- Adds a small formatting tweak so that we only show the URL’s host for non-Astro sites — should avoid super verbose output like in https://github.com/withastro/astro.build/pull/891
> Small showcase scraper script tweaks

- src/content/blog/astro-4-beta.mdx
Calls out `@astrojs/upgrade` (new!) and also corrects an issue with the previous `npm init astro@beta` instructions.
Closes https://github.com/withastro/astro/issues/9205
> Update 4.0 Beta upgrade instructions

- astro.config.mjs
- src/content/blog/_whats-new-components/ShowcaseCard.astro
- src/content/blog/_whats-new-components/ShowcaseGrid.astro
- src/content/blog/whats-new-december-2023.mdx
- src/content/blog/whats-new-november-2023.mdx
- src/content/blog/whats-new-october-2023.mdx
Adds a new `<ShowcaseGrid>` component that can be used in the “What’s New in Astro” blog post series to show a grid of links showing a screenshot of the site with information on focus/hover like we do in our existing showcase section. For example:
```mdx
{/* src/content/blog/example.mdx */}
import ShowcaseGrid from './_whats-new-components/ShowcaseGrid.astro';
export const sites = [
{ title: 'Example Site', url: 'https://example.com' },
{ title: 'Another Demo', url: 'https://demo.dev' },
];
<ShowcaseGrid items={sites} />
```
- I’ve updated all the preceding editions of the What’s New in Astro posts to use this component too: [October](https://astro-build-git-chris-month-in-astro-showc-d6d5f7-astrodotbuild.vercel.app/blog/whats-new-october-2023/#showcase), …
> Add showcase screenshot grid to “What’s New in Astro” blog posts

- src/content/themes/balanced-chef.md
Removing the demo link for the Balanced Chef theme.  I'll try to find a contact for the theme dev before removing the theme completely, it looks like the repo is still correct and the demo link was reused for a different theme
> removing Balanced Chef demo link

- src/styles/prose.css
- Fixes #955 
*(disregard the font change, local dev couldn't load fonts for some reason)*
> fix inline code and link style collision

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/content/blog/astro-025.mdx
- src/content/blog/astro-150.mdx
- src/content/blog/astro-250.mdx
- src/content/blog/astro-420.mdx
- src/content/blog/netlify-edge-functions.mdx
- src/styles/prose.css
- This PR adds the `astro-expressive-code` integration to add syntax highlight to diff code blocks.
- Adds `lang="js"` metadata to diff codeblocks.
- Updates blog posts with proper code block metadata
> feat: add expressive code to style code block diffs

- src/content/pages/telemetry.md
We now collect when toolbar apps are toggled, in order to know how much our apps are being used
> feat: add new telemetry event

- vercel.json
We have an existing `astro.build/config` redirect. Would be nice to have the same for DB stuff!
These are being used in https://github.com/withastro/astro/pull/10349 but don't exist yet.
> Add `/db/*` redirects

- src/components/BaseHead.astro
- src/pages/db/_components/HeroVideo.astro
- Load the DB hero image eagerly
- Remove MDIO from the font preload, it's always below the fold
> Tiny performance improvements

- src/pages/db/_components/Hero.astro
- src/pages/db/_components/Intro.astro
Since fully ends in `-ly`, it doesn't get hyphenated.
> Remove incorrect hyphen from "fully managed"

- src/pages/db/_components/Pricing.astro
- src/pages/db/_components/SectionText.astro
We've received a few questions on pricing. This adds a `#pricing` id to the DB pricing header so we have a permalink: https://astro.build/db#pricing
- Add `headingId` property to `SectionText`
- Apply pricing id
> chore: add heading id to pricing section

- src/pages/db/_components/FooterCTA.astro
- src/pages/db/_components/Hero.astro
- src/pages/db/_components/Intro.astro
- src/pages/db/_components/SectionText.astro
Font styles on https://astro.build/db are a bit broken at the moment. This updates the markup to use `font-heading` rather than the old `heading` class
<table>
<tr>
<td>
**Before**
</td>
<td>
**After**
</td>
</table>
> [DB] fix font styles

- .vscode/extensions.json
Adds MDX as a recommended extension, so VSCode / Gitpod users get prompted for an install
> chore: add MDX as recommended extension

- src/components/ImageGallery.astro
- src/pages/themes/_components/ThemeCard.astro
- src/pages/themes/details/[slug].astro
use `astro:assets` in theme detail pages
> fix: use compressed images in detail page

- src/pages/db/_components/Subnav.astro
The `IntersectionObserver` logic added to `/db` in #1059 consistently skipped highlighting the **Features** section. 
This PR refactors the logic to track the delta between ratios rather than using a naive `entry.isIntersecting` check.
Tiny perf improvement by hoisting the `selector` variable up, too.
> Improve DB intersection observer logic

- src/pages/index.astro
Follow-up to #1088, which broke for unknown reasons.
Implements a banner announcement for [**Astro Together**](https://lu.ma/astro-together-meetup-2024/). Please join us and 100+ Astro developer in Montreal on May 28th!
> Add meetup banner

- src/pages/_components/Hero.astro
Rather than linking the main CTA to https://docs.astro.build (which is another landing page), we should link directly to https://docs.astro.build/en/install/auto/. 
This PR implements that change.
> Adjust main CTA link

- src/pages/_components/Hero.astro
This restores the main CTA link back to pointing to the main docs landing page which offers users a more holistic set of options and information to get started with Astro.
The CTA was originally changed to avoid a double “Get started” => “Get started” sequence of CTAs when linking to the docs homepage, but we are updating that in https://github.com/withastro/docs/pull/8222 to add a better CTA once users land in docs.
> Revert "Adjust main CTA link (#1089)"

- src/content/blog/astro-480.mdx
There were a few points of confusion copy / pasting our code snippet as a React component. This resolves any of those issues. We also add a link to `getActionProps` documentation since it's been asked frequently on twitter.
> Update actions example to match React syntax

- src/content/blog/astro-490.mdx
Fixes a small typo (CRSF -> CSRF) in the 4.9 blog post.
> fix: CSRF typo in 4.9 blog post

- src/components/Footer.astro
- src/layouts/MainLayout.astro
- src/pages/db/index.astro
- src/pages/index.astro
Hot fix for a few issues introduced by #1110.
- Removes margin top from the Footer — this worked on the homepage but broke other layouts. Hotfix is a quick spacer div in the homepage layout so that that view is spaced correctly without breaking other pages
- Reverts the move to use a new `astro-dark` palette in some of our core layout components that was bleeding into other pages in ways that didn’t quite work. The homepage is still using this, but the other layouts use the background from before until a more comprehensive palette migration in those other views can be implemented (if indeed that is the goal)
> Fix footer margin & background colours

- .github/workflows/nightly.yaml
#1038 removed the `lint:prettier` script, but our Nightly CI was still using it, causing it to fail ever since (e.g. https://github.com/withastro/astro.build/actions/runs/9580083120/job/26413945456)
This PR updates the CI workflow to use the newer `lint` script that runs Biome instead.
> Fix nightly CI

- src/content/blog/whats-new-may-2024.mdx
This moves a theme from the themes component to a text link because the link in the themes catalogue is broken
> fixes broken URL in May 2024 blog post

- src/pages/_components/landing-page/Islands.astro
It's WordPress, not Wordpress. Overall the WP community is quite strict about this - there is even a function `capital_P_dangit` that changes Wordpress to WordPress in WP core.
Sorry for this PR (as it's a bit shitty and don't want to be a person that writes "use capital P", but...). Thanks :)
> A minor typo regarding WordPress on homepage

- scripts/update-showcase.mjs
**Summary:**
Adds the [timeout option](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback#timeout) to the `requestIdleCallback` when getting screenshots for showcase sites.
**Background:**
After opening #1157, I added a site to https://github.com/withastro/roadmap/discussions/521#discussioncomment-9904855, then ran the update-showcase script locally to see things run. The script timed out on the new site, due to requestIdleCallback not resolving. This probably has something to do with animations running on load and an idle state never being reached for this particular site.
Before | After
--- | ---
> Adjust timeout for showcase screenshots

- src/components/BaseHead.astro
- src/components/BlogSummary.astro
- src/components/CardBadge.astro
- src/components/SEO.astro
- src/layouts/MainLayout.astro
- src/layouts/Standalone.astro
1. Removing some "twitter" meta tags in order to use OG tags as fallback and reducing code size.
2. Removing unnecessary script (---) in some files.
3. Re-arranging "generator" and "theme-color" tags to load important resources faster (script, styles, fonts).
4. Removing "mask-icon" because it's unnecessary.
5. Changing class attribute from `html` to `body`, because the only elements that effected are flow and content elements which live under `body` element, so it's more straightforward and applicable.
Resources for:
OG and Twitter Card:
> Basically, you can use same sub-properties like title, description, image, image:alt, url and so on.
https://ogp.me/
https://developer.x.com/en/docs/twitter-for-websites/cards/guides/getting-started
Re-arranging some tags: …
> Removing some unnecessary meta tags, "mask-icon" and quick fixes

- package.json
- pnpm-lock.yaml
- scripts/integrations.mjs
- scripts/markdown.mjs
- scripts/update-integrations.mjs
- src/content/config.ts
- src/content/integrations/@astrojsmdx.md
- src/content/integrations/@astrojspartytown.md
- src/content/integrations/@astrojsprism.md
- src/content/integrations/@astrojssitemap.md
- src/content/integrations/@astrojstailwind.md
- src/content/integrations/@astropubicons.md
- src/content/integrations/@playformcompress.md
- src/content/integrations/@storyblokastro.md
- src/content/integrations/@unocssastro.md
- src/content/integrations/accessible-astro-components.md
- src/content/integrations/astro-compress.md
- src/content/integrations/astro-eleventy-img.md
- src/content/integrations/astro-i18next.md
- src/content/integrations/astro-icon.md
- src/content/integrations/astro-imagetools.md
- src/content/integrations/astro-json-element.md
- src/content/integrations/astro-robots-txt.md
- src/content/integrations/astro-seo.md
- src/content/integrations/astro-spa.md
- src/content/integrations/astro-xelement.md
- src/helpers/integrations.ts
- src/pages/integrations/[...page].astro
- Removes the concept of “featured” integrations entirely
We were not good about keeping this updated and download count is a reasonable proxy for popularity and what gets featured.
- Adds a new `downloadFactor` field to support downranking integrations with lots of downloads. This was needed for a couple of integrations that are bundled in some more popular package but don’t actually get used as much as the npm download count suggests. For example, `@astrojs/prism` is a dependency of `astro`, so is kind of automatically the “most popular integration”. But in reality only like 0.05% of Astro users actually enable it.
- Tweaked the wording in the integrations catalogue headings from “All integrations” to “Popular integrations”. This text only ever displays on the catalogue homepage and …
> Integrations catalogue tweaks

- src/pages/_components/landing-page/Ecosystem.astro
> Fix wordwrap

- src/content/blog/whats-new-july-2024.mdx
- Removes 1 broken youtube link titled `Let's build link in bio using astro, tailwind`
> Remove broken Youtube Link

- src/content/blog/astro-4130.mdx
This PR fixes the syntax highlighting for the latest minor release blog post and a wrong experimental flag name.
> Update Astro 4.13 minor blog post syntax highlighting and flag

- src/pages/_components/landing-page/Hero.astro
Updates the text/URL of the small banner in the hero pointing to the latest blog post
- [X ] Chrome / Chromium
> update landing page hero for 4.14

- astro.config.mjs
- package.json
This PR updates how Astro DB and the web vitals configuration are added, so that local builds can be run without needing to link to Astro DB. This helps contributors who are not members of the Astro organisation on Astro DB and can’t link in the first place.
n/a — no site code touched
> Fix local builds if Astro DB is not linked

- package.json
- pnpm-lock.yaml
Fixes an issue with on-demand optimized images.
> Move `sharp` back to prod dependencies

- src/content/blog/astro-4100.mdx
- src/content/blog/astro-4120.mdx
- src/content/blog/astro-4140.mdx
- src/content/blog/netlify-official-deployment-partner.mdx
- src/content/config.ts
- src/pages/_components/LatestBlogPostLink.astro
- src/pages/_components/landing-page/Hero.astro
This PR automates the homepage link to the latest blog post by adding a new `homepageLink` field to blog post frontmatter.
A blog post can include this and if it is the most recent post, it will automatically be used for the link on the landing page. For example, frontmatter can include something like
```yml
homepageLink:
title: Astro 4.14
subtitle: New experimental Content Layer API
```
And the homepage will render it as 
From what I could tell, we forgot to update this every single time we blogged for the last 2 months, so seems worth integrating it into the blog post frontmatter instead.
If a blog post is not considered important enough to link from the homepage, you can simply omit `homepageLink` and the post will be ignored.
I have tested this PR on at least three of the following …
> Automate homepage link with frontmatter field in blog posts

- src/helpers/path.ts
Fixes a bug in pagination when the URL contains a search parameter.
> Account for search params and hash in trailing slash utility

- src/content/blog/astro-4140.mdx
I kept getting the following error while following the instructions in the blog post to try out the new Content Layer API on a newly created Astro project (created using `pnpm create astro@latest`).
```
❯ pnpm run dev
> notion-loader-test@0.0.1 dev /Users/crcastle/Code/github.com/crcastle/notion-loader-test
> astro dev
2:46:57 PM [vite] Error when evaluating SSR module /Users/crcastle/Code/github.com/crcastle/notion-loader-test/astro.config.mjs: failed to import "astro"
|- SyntaxError: [vite] The requested module 'astro' does not provide an export named 'defineConfig'
at analyzeImportedModDifference (file:///Users/crcastle/Code/github.com/crcastle/notion-loader-test/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.0/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:51946:15)
at nodeImport …
```
> Fix incorrect path in example code in Astro 4.14 blog post

- src/content/config.ts
- src/data/authors/authors.json
This PR removes the unused `title` property from the Astro blog's authors data.
> Remove titles from `authors.json` data

- src/pages/_components/LatestBlogPostLink.astro
This PR fixes the URL used for the homepage latest blog post link to use a relative `/blog/[slug]` URL instead of the current absolute `https://astro.build/` URL.
This means it will also work in deploy previews and locally.
As requested by @Princesseuh 🫡 
> Make pill link on homepage relative

- src/content/blog/astro-4140.mdx
Looks like the RFC number changed from 47 to 50.
> Fix 404 link in Astro 4.14 blog post

- src/components/SEO.astro
- src/content/config.ts
- src/data/authors/authors.json
- src/pages/blog/[slug].astro
This PR adds some extra metadata for Google search:
- Adds a `<meta name="robots" content="max-image-preview:large" />` tag to permit large image previews in search results — most pertinent to Chrome’s “Discover” view ([docs](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#max-image-preview), [case study](https://developers.google.com/search/case-studies/large-images-case-study)).
- Adds JSON-LD structured data for blog posts to help Google find the right image to display ([docs](https://developers.google.com/search/docs/appearance/structured-data/article)).
- In the process, tweaked our authors metadata slightly to ensure we had a URL for each author by adding an optional `github` URL field to the data (and ensuring all URLs in the author schema are correctly …
> SEO improvements for blog posts

- src/components/BlogSummary.astro
- src/content/blog/astro-4100.mdx
- src/content/blog/astro-4110.mdx
- src/content/blog/astro-4120.mdx
- src/content/blog/astro-4130.mdx
- src/content/blog/astro-4140.mdx
- src/content/blog/astro-4150.mdx
- src/content/blog/astro-450.mdx
- src/content/blog/astro-460.mdx
- src/content/blog/astro-470.mdx
- src/content/blog/astro-480.mdx
- src/content/blog/astro-490.mdx
- src/content/blog/dev-portal.mdx
- src/content/blog/future-of-astro-content-layer.mdx
- src/content/blog/future-of-astro-server-islands.mdx
- src/content/blog/future-of-astro-zero-js-view-transitions.mdx
- src/content/blog/goodbye-astro-studio.mdx
The `<BlogSummary>` component was added in #1003 to highlight the opening section. However, since then it has been incorrectly used on 15 occasions, resulting in odd markup and not the intended visual style.
This PR does the basic thing and rips it out entirely in favour of simply bolding the opening paragraphs like we already do in some other blog posts.
> Remove `<BlogSummary>` component

- src/content/blog/astro-5-beta.mdx
Adds the `create astro` command for starting a new 5.0-beta project to the announcement blog post.
> Add create astro command to 5.0-beta blog post

- scripts/integrations.json
- src/content/integrations/@studiocmsblog.md
- src/content/integrations/studiocms.md
StudioCMS was recently renamed from `@astrolicious/studiocms` to `studiocms`.
This PR fixes the image link between the packages and their respective image, this is using the same image from #1214
> Update StudioCMS Image on Integration list

- src/content/blog/cloudinary-loader.mdx
- src/content/blog/hygraph-loader.mdx
- src/content/blog/storyblok-loader.mdx
Removes the `homepagelink:` frontmatter property from blog posts published after 5.0 beta, to keep the homepage linking to that post.
> remove homepage links

- package.json
- pnpm-lock.yaml
- scripts/npm.mjs
- scripts/update-integrations.mjs
- Update integrations in parallel, reduce the time for `update:integrations --unsafe` from 4 minutes to 10 seconds
- Use `p-limit` to avoid rate-limit errors by limiting the number of concurrent calls to NPM API to 10
- `p-limit` is a already a dependency of Astro, so it is not an extra dependency to install
> Fetch integration data in parallel for update

- src/pages/_components/landing-page/ZeroJsFeatureCard.astro
animate the zero js card on the landing page (#1131)
> add animation to zero js card on the landing page

- src/content/blog/cloudinary-astro-sdk-launch.mdx
We worked with Cloudinary for a short time period to help push the Astro Cloudinary SDK. Now that that is over, remove Cloudinary SDK link and return home page pill to Astro 5.0 (or whatever we want to promote).
> Remove Cloudinary from home page pill

- src/components/charts/CWVCLSChart.astro
- src/content/blog/_whats-new-components/ShowcaseCard.astro
- src/helpers/themes.ts
- src/pages/integrations/_components/IntegrationCard.astro
- src/pages/showcase/_components/ShowcaseCard.astro
- src/pages/themes/_components/ThemeCTAs.astro
Our showcase and integration catalogues link to a bunch of external resources.
This PR adds `rel="nofollow ugc"` to these to reduce their value to the external site in terms of SEO (see [“Qualify your outbound links to Google”](https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links)).
We’ve had a few signs of potential inauthentic activity using these catalogues, so worth adding these I think to discourage that.
> Add `rel="nofollow ugc"` to links to external showcase sites and integrations

- package.json
- pnpm-lock.yaml
- scripts/npm.mjs
- scripts/update-integrations.mjs
This PR fixes our script which updates integrations based on the npm registry.
We use a search endpoint in the npm registry API to look up integrations with one of our keywords. Previously we did this with a single call combining keywords into the query parameter: `text=keyword:astro-component,withastro,astro-integration`.
Some time around November 30, the response to this query changed. It looks like previously npm treated the list of keywords as “one of these” (i.e. OR), but is now treating it as “all of these” (i.e. AND). This meant our query only returned the ~100 packages that include all three keywords and the script tried to delete all the others we knew about.
This PR updates the script to run the search query separately for each keyword. This caused some “too many request” errors …
> Fix integrations script

- src/content/config.ts
As discussed on Discord, this PR ensures that the showcase titles are not "Just a moment..." by enforcing that in the `showcase` collection schema.
This title usually means that fetching infos was blocked, e.g. on Cloudflare hosted sites and that the title will need to be updated manually.
Happy to discuss the wording of the error message as usual.
I have tested this PR by building the website locally to ensure no entries have the title "Just a moment...".
I also changed the title of one of the showcase entries to "Just a moment..." to ensure that the build fails.
This change does not affect the browser output.
> Ensure showcase titles are not "Just a moment..."

- src/pages/_components/landing-page/Teams.astro
- src/pages/integrations/[...page].astro
- src/pages/showcase/[...page].astro
- src/pages/themes/[...page].astro
- src/pages/themes/_components/Avatar.astro
- src/pages/themes/_components/Badge.astro
This PR fixes a few tiny design details in a few spots I’ve noticed while reviewing other work the last few days.
- Fixes some awkward wrapping of the bottom part of theme cards in the theme catalogue.
| Before | After |
|---|---|
| ![three theme cards, their footer text wraps awkwardly in the narrower layout](https://github.com/user-attachments/assets/b468f880-bdb0-4f5b-b159-7ade269c8ec4) | ![the same theme cards, now their footer text sits on a single line, truncated with ellipses when necessary](https://github.com/user-attachments/assets/442d7fe0-9b26-4725-880d-7a973f86dacd)
- Fixes some slightly tight spacing around the “used by” company logos on the homepage. This change also ensures we never have a layout where just one logo is wrapped by itself on to the second row.
| Before | …
> Small design detail tweaks

- src/pages/themes/details/[slug].astro
This PR fixes an issue where themes with only 1 extra image would not display the extra image.
The default image is defined in the `image` field of a `Theme` object and extra images are defined in the `images` array. The current condition to display the image gallery component is `theme.Theme.images.length > 1` which is incorrect as it means that the gallery component will not be displayed if there is only 1 extra image.
This PR fixes the issue by changing the condition to `theme.Theme.images.length > 0` so that the gallery component will be displayed if there is at least 1 extra image (and bring it on par with the condition [used in the portal UI](https://github.com/withastro/astro-dev-portal/blob/c375f9e2d7b6118cfafc78587dff503e0ea4190e/apps/site/src/pages/themes/%5Bslug%5D.astro#L85)) …
> Ensure that themes with exactly 2 images display both images

- tailwind.config.ts
This plugin was always misconfigured and the same CSS was added correctly in `tailwind.css`.
> Remove unnecessary Tailwind plugin

- .github/renovate.json5
I noticed that when we release linked patches for multiple Astro packages (e.g. Astro + Netlify adapter + MDX integration) each of these will generate a separate PR when probably merging them together makes sense. IIUC this config change should group `astro` and `@astrojs/**` packages together into a single Renovate PR to keep them in sync and reduce the number of PRs to wrangle.
(I also reformatted the file to regular JSON as my editor was complaining about the `.json5` formatting and I guess that would be the same for other contributors.)
> Group Astro dependencies in a single update for Renovate

- src/pages/themes/[page].astro
Updating the number of themes shown per page.
This allows more themes to be discovered without the friction of navigating to a new page.
> Update to 18 themes per page

- src/content/blog/astro-560.mdx
- src/styles/prose.css
> fix: blog prose styles

- src/pages/themes/author/[id]/[...page].astro
This PR introduces dynamic `title` and `description` for the author page to improve SEO and Open Graph metadata.
> Dynamically generate seo metadata for theme author pages

- src/pages/themes/[page].astro
Fixes the first two links here:
> Fix pagination link to /themes/1/

- astro.config.mjs
- src/styles/prose.css
This PR enables Expressive Code’s `frames` feature, which includes file titles and copy code buttons.
I disabled it by default still for `sh`, `bash`, and `shell` code blocks to not add the terminal window bar (but this can still be added back with a `frame="terminal"` attribute if we ever need it).
In blog post code blocks that included a filename at the top of a snippet (e.g. `// astro.config.mjs`), these will now show that filename in the snippet title bar.
> Enable Expressive Code’s `frames` feature

- src/pages/_components/landing-page/IntegrationContent.astro
We added some additional Expressive Code styles in #1514, but I missed that we were using it on the homepage too. @hippotastic spotted that the new styles clashed with the homepage usage. This PR fixes that.
> Fix code block styling on landing page

- src/pages/themes/details/[slug].astro
Handle 404s from portal to prevent the route from crashing if a theme does not exist.
> Handle API 404 on theme details

- public/_redirects
Adds a redirect from `/llms.txt` to the docs site.
> Add redirect for llms.txt

- src/pages/_components/landing-page/ecosystem-tabs/Blogs.astro
- src/pages/_components/landing-page/ecosystem-tabs/Docs.astro
- src/pages/_components/landing-page/ecosystem-tabs/Ecommerce.astro
- src/pages/_components/landing-page/ecosystem-tabs/LandingPages.astro
- src/pages/_components/landing-page/ecosystem-tabs/Portfolios.astro
- src/pages/_components/landing-page/ecosystem-tabs/Trending.astro
This PR fixes links in the “Ecosystem: Themes” section on the astro.build landing page.
Two fixes are included:
- Some tabs in this section include “Browse more…” links. These were no longer working as intended since we moved the full catalogue to `/themes/1/` instead of `/themes/`. This PR updates those links to point to `/themes/1/`.
- Links in these components were hardcoded to use `astro.build` origins meaning they’d take you out of a dev/preview environment if you clicked one. This PR changes them to relative links to avoid that.
> Fix theme links in landing page component

- .github/workflows/weekly.yaml
This PR downgrades the version of Ubuntu used to run our showcase update workflow.
#1611 updated this, but it’s causing Puppeteer to fail in that workflow: https://github.com/withastro/astro.build/actions/runs/16646443672/job/47108742183
> Downgrade Ubuntu in showcase update workflow

- scripts/fetch.mjs
- scripts/npm.mjs
- scripts/update-integrations.mjs
Our integrations update script that runs each week fetches the homepage URL reported by NPM to double check it’s not a 404 (or other error). This was previously done concurrently inside one massive `Promise.all()`. Unsurprisingly, we’ve been seeing false negatives with GitHub in particular returning errors due to us spamming them even when the repo URL is valid.
This PR updates those fetches to have a maximum concurrency of 10 requests at a time and to retry on errors just to be sure an error is not a fluke.
> Limit concurrency & retry errors when testing for integration 404s

- .github/workflows/nightly.yaml
- .github/workflows/weekly.yaml
This PR updates our weekly and nightly GitHub Actions workflows to commit as Houston rather than the default of whoever created/last committed.
> Use Houston as commit author for weekly and nightly workflows
