public/styles/main.css
src/components/landing/Demo.astro
src/components/landing/Hero.astro
src/components/landing/Performance.astro
src/components/landing/Sponsors.astro

Attempting to see if `content-visibility: auto` help improve scroll performance

Use `content-visibility` to contain expensive paints

---

src/components/BaseHead.astro
src/pages/blog/[...slug].astro
src/pages/blog/index.astro
src/posts/astro-018.md
src/posts/astro-019.md
src/posts/astro-021-preview.md
src/posts/astro-021-release.md
src/posts/astro-repl.md
src/posts/demo-day-2021-09.md
src/posts/index.ts
src/posts/introducing-astro.md
src/posts/netlify-astro-hosting-sponsorship.md
src/posts/the-astro-technology-company.md

Huge thanks to @rbardini for https://github.com/withastro/astro/pull/2301!
Unfortunately this contribution was dropped in the upgrade to the new site. Now our RSS feed is back!

Add RSS feed for /blog

---

src/components/Nav.astro

add repl link to the new websites navbar

add repl link to the new websites navbar

---

src/components/landing/Hero.astro

Many folks have reported severe performance issues. The hero animation is the most likely cause, so this removes that.

Remove hero animation

---

src/posts/experimental-static-build.md

This post is meant to:
- Tell people in the wider Astro community about the static build and the benefits.
- Let them know that this is going to the main build in the future.
- Encourage them to report bugs so we can stabilize it enough to make it the main build.

Blog post on the new static build

---

src/posts/astro-023.md

Includes `import.meta.env` updates in the 0.23 guide

Update 0.23 guide

---

src/data/showcase/tkon.json

Just changing the title to the title of the website (my name) and the domain to the production one.

Small fix to my showcase entry

---

src/components/Nav.astro
src/config.ts

- I keep not knowing which links live where, so I took a pass at the header links on the site. 
- I think this makes more sense!

new nav layout

---

scripts/github.mjs
scripts/integrations.json
scripts/update-integrations.mjs
src/components/PillList.astro
src/data/integrations.json

Adding an integration collection for framework renderers

---

src/pages/blog/astro-1-beta-release.md

Linking back to release update from the beta announcement

Update beta post

---

package.json
pnpm-lock.yaml
public/robots.txt
src/components/BaseHead.astro

- updates to the latest build deps
- updated to support the `sitemapindex` setup in `@astrojs/sitemap@0.2.0`

Chore: Update site dependencies

---

src/components/Search.astro

Updates the search bar used on integrations to use a `<label>` for better accessibility and automatically focus the input on click

Updating search bar markup for proper accessibility

---

src/components/Mention.astro

Very hacky quick fix, we really should refresh the styling setup for blog posts

hotfix: spacing in Mention component in a blog post

---

pnpm-lock.yaml
src/data/integrations.json
src/data/themes.json

PNPM lock file was out of sync and blocking our nightly data fetch - updating the lock file and pulling fresh data from NPM and GitHub

fixing lock file and updating nightly data fetch

---

package-lock.json
package.json

Hopefully this fixes smoke tests on the main `astro` repo!

Bump `astro-icon`

---

astro.config.mjs
package-lock.json
package.json
public/styles/main.css
src/components/BaseHead.astro
src/components/ContributorsAvatarList.astro
src/components/FlyoutMenu.astro
src/components/MobileMenu.astro
src/components/MobileMenuGroup.astro
src/components/Nav.astro
src/components/landing/Sponsors.astro
src/layouts/Content.astro
src/layouts/Legal.astro
src/layouts/Post.astro
src/styles/tailwind.css

Updates to the Astro RC!
- migrating old `Astro.canonicalURL` references
- adds legacy markdown flag
- fixes a few style regressions related to specificity changes

Updating to the RC :tada:

---

scripts/integrations.json
scripts/integrations.mjs
scripts/update-integrations.mjs
src/data/integrations.json

Updates how the npm search nightly job filters official packages

---

src/layouts/Base.astro
src/pages/themes/details/[slug].astro

Accessible at the route `/themes/details/placeholder`

Theme detail mockup

---

src/pages/index.astro

Fixed the alphine js link to point to correct page.

Fixed the alphinejs link to point to correct page.

---

src/data/themes.json
src/data/themes/agnostic-ui.json
src/data/themes/astroship.json

Moves Astroship to the featured list

Updating the list of featured themes

---

src/pages/404.astro

Bubbles up 404 events to Fathom Analytics

Adds 404 event tracking

---

src/data/themes.json
src/data/themes/accessible-astro-starter.json
src/data/themes/art-portfolio.json
src/data/themes/astro-big-doc.json
src/data/themes/astro-boilerplate.json
src/data/themes/astro-business-template.json
src/data/themes/astro-design-system.json
src/data/themes/astro-ink.json
src/data/themes/astro-landing-page.json
src/data/themes/astro-neumorphismt.json
src/data/themes/astro-paper.json
src/data/themes/astro-portfolio.json
src/data/themes/astrolus.json
src/data/themes/astroship.json
src/data/themes/astrowind.json
src/data/themes/basics.json
src/data/themes/blog.json
src/data/themes/cannonball.json
src/data/themes/creek.json
src/data/themes/docs.json
src/data/themes/hello-astro.json
src/data/themes/index.ts
src/data/themes/modern-personal.json
src/data/themes/odyssey.json
src/data/themes/portfolio.json
src/data/themes/pro-file.json
src/data/themes/tailcast.json

[x] removes "official" collection
[x] adds docs, landing page, and portfolio
[x] updates the order of themes on the featured tab

Updates the list of theme collections

---

scripts/github.mjs
scripts/update-themes.mjs
src/components/ThemeCard.astro
src/data/integrations.json
src/data/themes.json
src/data/themes/linked-up.json
src/data/themes/odyssey.json
src/data/themes/pro-file.json
src/pages/index.astro
src/pages/themes/details/[slug].astro
src/types.ts

Links are dynamically picked up by repoUrl.  For paid repos (without a public repo) `author` can be set directly in theme's JSON data file

Adds support for theme author links

---

public/.well-known/webfinger
src/components/BaseHead.astro

For federated social networking, points to our [`@astro`](https://m.webtoo.ls/@astro) account on `webtoo.ls`

Add webfinger

---

astro.config.mjs
package.json
pnpm-lock.yaml
src/components/BaseHead.astro
src/data/site.ts
src/types.ts

Did someone say [IndieWeb](https://indieweb.org)?

Adds `astro-webfinger` integration and extra rel="me" links

---

public/_redirects
src/pages/themes/submit/index.astro

Using a Netlify redirect here so we can swap out the Figma link later

Adds a link to our Image Templates on the theme submit page

---

src/data/themes.json
src/data/themes/cannonball.json
src/data/themes/littlesticks-simple-blog.json
src/data/themes/odyssey.json
src/data/themes/pro-file.json

Littlesticks moved from Gumroad to LemonSqueezy for theme sales

Updating Pro File theme's buy URL

---

public/_redirects

Needed for https://github.com/withastro/astro/pull/5855

Add `/issues/compiler` redirect

---

src/content/blog/astro-2.mdx

Release post typo

---

src/content/blog/introducing-content-collections.mdx

Just so the post ordering is correct!

Update Content Collections publish date

---

src/data/authors/thuy.json

Update Thuy's author json with Twitter profile

---

src/components/HeaderNav.astro
src/pages/press/index.astro

Does what it says in the title.

Point contextmenu to `/press#assets` directly

---

package.json
pnpm-lock.yaml
src/pages/_components/Hero.astro
src/pages/blog/[slug].astro
src/pages/integrations/[...page].astro
src/pages/showcase/[...page].astro
src/pages/themes/[...page].astro
src/pages/themes/submit/index.astro

Looks like an update in the zod types broke one of our `z.instanceof()` uses

Fixing linter error in zod message format

---

src/content/blog/2023-web-framework-performance-report.mdx

Small correction in 2023-web-framework-performance-report.mdx

Fix sentence in 2023-web-framework-performance-report.mdx

---

src/content/blog/astro-210.mdx

2.1 post - code sample typo

---

astro.config.mjs
houston.theme.json

It's more on brand™
**Before**
**After**

Use Houston code theme

---

src/components/Prose.astro

| before | after |
| --- | --- |
| ![](https://user-images.githubusercontent.com/19603573/224378760-5c64f33a-ef47-46ea-a6e0-ce4a386d5362.png) | ![](https://user-images.githubusercontent.com/19603573/224381250-0d03a22c-433d-42b1-8bd6-9fc500f3a931.png) |

Prose: style tweaks for code

---

astro.config.mjs
package.json
pnpm-lock.yaml
src/components/Footer.astro
src/components/HeaderDrawerContent.astro
src/components/HeaderNav.astro
src/components/Pagination.astro
src/components/ResourcesMenu.astro
src/components/SearchFilter.astro
src/layouts/MainLayout.astro
src/pages/404.astro
src/pages/_components/ToolingAndEcosystem.astro
src/pages/about/index.astro
src/pages/blog/[...page].astro
src/pages/blog/_components/BlogPostPreview.astro
src/pages/careers/_components/CareersList.astro
src/pages/careers/index.astro
src/pages/integrations/[...page].astro
src/pages/showcase/_components/SubmitSite.astro
src/pages/themes/[...page].astro
src/pages/themes/_components/ThemeCard.astro
src/pages/themes/details/[slug].astro
src/pages/themes/submit/success.astro

Added rel="prefetch" wherever I thought it made sense

add prefetch links

---

src/pages/_components/Sponsors.astro

CloudCannon requested that the logo href be the UTM link for our Astro x CloudCannon page 🌈

Update CloudCannon sponsor logo href

---

scripts/update-showcase.mjs

Not 100% sure this is the correct fix but would like to try running this branch to find out!

Fix showcase script with internal Puppeteer Chromium download API

---

src/content/blog/astro-210.mdx

Fixed InferGetStaticParamsType to actually use the Params type in example code

Fixed InferGetStaticParamsType to actually use the Params type

---

src/layouts/MainLayout.astro

A future PR will add support for an expiration date where notification banners will automatically be hidden

Hides the notification banner (temp)

---

src/content/themes/industronix.md

updating the buy URL for the Industronix theme

---

src/content/blog/astro-140.mdx

Fixes relative link to `#better-control-over-style-editing`

update broken link in 1.4 blog post

---

src/content/blog/astro-240.mdx

Did you mean 'server' instead of 'ssr' for the output config?

output: 'server' vs 'ssr'

---

pnpm-lock.yaml
src/components/BaseHead.astro

Updating the URL used for loading Fathom's analytics script to avoid using custom subdomains

chore: Fathom analytics update

---

src/content/blog/astro-260.mdx

Fixes the update commands shown in the 2.6 blog post.

Fix update commands in 2.6 blog post

---

src/content/blog/astro-260.mdx

This fixes a minor typo in the middleware code example.

Fix middleware code example in 2.6 blog post

---

.prettierignore
src/components/Callout.astro
src/components/CatalogSubmitCallout.astro
src/components/Checkbox.astro
src/components/CodeBlock.astro
src/components/Footer.astro
src/components/TextInput.astro
src/layouts/MainLayout.astro
src/pages/404.astro
src/pages/[slug].astro
src/pages/_components/CoreWebVitalsGraphItem.astro
src/pages/_components/ExampleShowcase.tsx
src/pages/_components/Hero.astro
src/pages/_components/ToolingAndEcosystem.astro
src/pages/blog/[...page].astro
src/pages/blog/[slug].astro
src/pages/blog/_components/BlogPostPreview.astro
src/pages/careers/[slug].astro
src/pages/press/_components/PressAssetCard.astro
src/pages/press/index.astro
src/pages/themes/_components/SubmitTheme.astro
src/pages/themes/details/[slug].astro
src/pages/wallpapers/index.astro
src/styles/prose.css

Looks like a tweak in the prettier config for Tailwind class name ordering was hitting our CI lint checks

chore: fixing a few linter errors

---

src/components/BaseHead.astro
src/components/SEO.astro

Gotta have that streamlined head 👨‍🦲 
I'm not sure this catches everything that https://github.com/rviscomi/capo.js flagged, but it should improve the order?

Reorder BaseHead to prioritize order

---

public/_redirects

Just adding a redirect for use in `create-astro`

Add `/examples` redirect

---

tsconfig.json

I know that this isn't the biggest / important change, but it's nice to keep everything consistent

chore: switch out directories in `tsconfig`

---

src/content/pages/telemetry.md

Set last updated date on `/telemetry` to last Monday, 28 August.

Update last updated date on `/telemetry`

---

src/content/blog/viteconf-2023.mdx

Update ViteConf post

---

README.md

hello,
just fixing a small typo i stumble onto while browsing the code

fix: typo on readme for integration page

---

src/content/blog/whats-new-october-2023.mdx

Updates the Monthly post with up-to-the-minute content!

add newsletter and updated Hacktoberfest stats to Oct 2023 monthly post

---

src/content/themes/astro-identity.md
src/content/themes/astropod.md
src/content/themes/launchfast.md
src/content/themes/milky-way.md
src/content/themes/stone.md
src/pages/themes/[...page].astro

Updating the buy now, email, and Twitter links per request by the theme author

Updates to the LaunchFa.st theme

---

src/pages/api/v1/integrations/[...page].ts

Fix CORS on integrations endpoint

---

src/content/config.ts
src/helpers/integrations.ts
src/pages/api/v1/dev-overlay/[...page].ts

Overlay endpoint was returning an empty array. I fixed up the logic!

Update overlay endpoint

---

src/content/blog/astro-4-beta.mdx

We can walk back the title change if it doesn't look as good split on two lines

Improve meta tags on Astro 4 blog post

---

src/components/Avatar.astro
src/pages/_components/QuoteCard.astro
src/pages/blog/[slug].astro
src/pages/blog/_components/BlogPostPreview.astro

small style tweaks, mainly for mobile

---

src/content/caseStudies/wp-engine/index.mdx

Accidentally left an old meta description in. Replaced with relevant meta description.

Update WP Engine meta description for case study.

---

src/content/blog/images.mdx

typofix on Images

---

src/content/themes/astrowind.md
src/content/themes/author.md
src/content/themes/b2b-saas-kit.md
src/content/themes/carbon.md
src/content/themes/carriera.md
src/content/themes/cmd_theme.md
src/content/themes/flaco.md
src/content/themes/kotei.md
src/content/themes/phanatik.md
src/content/themes/profoliox.md
src/content/themes/simplexity.md
src/content/themes/williamsburg.md

Follow-up to #837, this adds the published date to the recently added Lexington Themes templates and updates the list of themes tagged as "NEW" in the recently added collection

Updating list of recently added themes

---

src/content/caseStudies/thinkmill/index.mdx

Includes a couple links and rewording some sections to better reflect their lived experience.

Apply Thinkmill's edit suggestions

---

src/content/blog/astro-420.mdx

Fix prerender doc link

---

.github/actions/install/action.yml
.github/workflows/blog.yml
.github/workflows/lint.yaml
.github/workflows/nightly.yaml
.github/workflows/weekly.yaml

Updates deprecated Node.js 16 github actions

---

src/pages/db/_components/Hero.astro
src/pages/db/_components/Pill.astro

Clarifies that we still consider Astro DB an early preview!
[`@astrojs/db`](https://www.npmjs.com/package/@astrojs/db) is still a v0 release, despite being well on the road to v1.
While we consider the API surface quite stable, we know that there will be edge cases to fix and room for overall improvement.
Please share your feedback! We welcome issues for both [Astro Studio](https://github.com/withastro/astro) and the [`@astrojs/db`](https://github.com/withastro/astro/issues) open source project.

Clarify DB landing page

---

src/pages/themes/[...page].astro

fix: persistence in filter

---

.env.example

Thought this might be helpful to know 😅

add .env.example

---

.github/actions/setup-node-pnpm/action.yml
.github/workflows/blog.yml
.github/workflows/format-main.yml
.github/workflows/nightly.yaml
.github/workflows/pr-checks.yaml
.github/workflows/weekly.yaml
scripts/migrate-integrations.mjs
scripts/update-integrations.mjs
src/components/Collapse.tsx
src/components/form/DropdownMultiSelect.tsx
src/helpers/discord.ts
src/helpers/integrations.ts
src/icons/integrations/index.ts
src/pages/_components/ExampleShowcase.tsx
src/pages/api/showcase.json.ts
src/pages/api/v1/integrations/[...page].ts
src/pages/rss.xml.ts
src/pages/themes/submit/_components/ThemeImageUploader.tsx
tsconfig.json

Adds the CI workflows to run on PRs, also organizes imports and other small lint/typecheck fixes. After this merges, I'll add the actual merge requirement rules in the repo

new ci workflows

---

src/pages/_components/ToolingAndEcosystem.astro

Update the Discord member number

chore: update Discord member number

---

package.json
pnpm-lock.yaml
scripts/npm.mjs
scripts/update-integrations.mjs

Fixes the integration updater failing in CI, improves some JSDoc types, and extracted some repeated code into a function. Tested locally to verify that it works as expected

fix update integration script

---

src/components/Header.astro
src/helpers/disclosure.ts
src/helpers/emitter.ts
src/layouts/MainLayout.astro
src/pages/db/_components/Hero.astro
src/pages/db/_components/HeroVideo.astro
src/pages/db/index.astro

- Adds a transparent style navbar
- Updates the `/db` page to use it
- Updates the `/db` page to improve hero image loading experience

Add support for transparent nav bar

---

src/pages/db/_components/UseCase.astro
src/pages/db/_components/use-cases/Comments.astro

Quick follow-up to #1050 to make the examples non-interactive (inert). Currently working on the interactivity in a follow-up PR.

[DB] make examples inert

---

src/content/blog/whats-new-march-2024.mdx

Malformed link in one of the content pieces

link fix: March 2024 blog post

---

src/components/ImageGallery.astro
src/icons/integrations/index.ts
src/pages/themes/[...page].astro
src/pages/themes/_components/Avatar.astro
src/pages/themes/_components/ThemeCTAs.astro
src/pages/themes/_components/ThemeCard.astro
src/pages/themes/_components/ThemeStats.astro
src/pages/themes/_types/index.ts

Adds the DB types as actual types

fix: make DB fetched types typesafe

---

src/content/blog/whats-new-march-2024.mdx

It looks like my username is wrong in the list of Community awards from march. This pull request updates it to the correct handle (@sasoria).

Correct username that recieved a community award

---

src/content/blog/future-of-astro-server-islands.mdx

This fixes a few typos and issues with the Server Islands blog post

Server Islands blog post improvements

---

scripts/update-showcase.mjs

This PR adds some new sites to the showcase blocklist as they were not built with Astro.

[showcase script] Adds new URLs to the blocklist

---

src/content/blog/whats-new-june-2024.mdx

Two YouTube links were mislabelled!

Fix links in June monthly blog post

---

vercel.json

Updated Discord link with the new invite link

---

src/content/blog/astro-4120.mdx

Adds a note on the changes to partialprerendering.com.

Add note on the benchmarks

---

src/components/BaseHead.astro
src/components/BlogSummary.astro
src/components/CardBadge.astro
src/components/SEO.astro
src/layouts/MainLayout.astro
src/layouts/Standalone.astro

Reverts withastro/astro.build#1181

Revert "Removing some unnecessary meta tags, "mask-icon" and quick fixes"

---

public/assets/integrations/bag-of-tricks.svg
scripts/integrations.json
src/content/integrations/astro-vtbot.md

adds bag-of-tricks logo to astro-vtbot integration

---

src/content/blog/astro-4150.mdx

Fix version typo in blog post

---

src/pages/_components/landing-page/Islands.astro

Update real-world core web vitals with the latest data from cwv report [View the full dataset](https://lookerstudio.google.com/u/0/reporting/55bc8fad-44c2-4280-aa0b-5f3f0cd3d2be/page/M6ZPC?params=%7B%22df44%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580WordPress%25EE%2580%2580Next.js%25EE%2580%2580Nuxt.js%25EE%2580%2580Gatsby%25EE%2580%2580Astro%25EE%2580%2580SvelteKit%25EE%2580%2580Remix%22%7D)
Closes #1267 

Update home page islands section with latest cwv scores

---

src/content/blog/cloudinary-astro-sdk-launch.mdx

A blog announcing that Astro is a proud launch partner for the Cloudinary x Astro SDK.

Cloudinary x Astro SDK launch blog

---

src/pages/_components/landing-page/Features.astro

Just noticed this URL isn't working anymore

fix URL in Actions FeatureCard

---

src/pages/_components/landing-page/Islands.astro

Update Real-World Core Web Vitals scores per sept 2024 data

Update CWV scores per sept 2024 data

---

src/content/blog/whats-new-october-2024.mdx

Add Inox Tools entry to October 2024 post

---

src/pages/_components/landing-page/Intro.astro

Fix typo in Server first intro

---

src/pages/_components/landing-page/Islands.astro

update CWV scores with Oct tech report [data](https://lookerstudio.google.com/u/0/reporting/55bc8fad-44c2-4280-aa0b-5f3f0cd3d2be/page/M6ZPC?params=%7B%22df44%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580WordPress%25EE%2580%2580Next.js%25EE%2580%2580Nuxt.js%25EE%2580%2580Gatsby%25EE%2580%2580Astro%25EE%2580%2580SvelteKit%25EE%2580%2580Remix%22%7D)

update CWV scores with Oct data

---

src/content/blog/astro-510.mdx

Fix publish date of astro-510.mdx

---

src/content/blog/whats-new-december-2024.mdx

Add link to article about the inner workings of Runtime Logger from Inox Tools

Add Inox Tools writeup to December 2024 blog post

---

src/pages/_components/landing-page/Sponsors.astro

Updates the link for our newest sponsor, LuckyMedia

Update LuckyMedia sponsor link

---

src/pages/themes/_components/ThemeAuthorProfile.astro

Fix formatting

---

public/assets/integrations/zikojs.svg
scripts/integrations.json

INTEGRATION : Add logo to ziko-wrapper addon 

---

src/content/blog/whats-new-february-2025.mdx

Realized I wasn't making good use of our Related Posts component!

Add previous related posts to Feb showcase post

---

src/content/pages/partnerships.mdx

Fix X/Twitter Link on Sponsorship Page

---

.github/renovate.json5

This PR adds renovate to the repository, with a minimal configuration to update github actions to use the commit digest. 

chore: add renovate to the project

---

src/content/blog/astro-570.mdx

Fix code fence in blog

---

src/content/blog/whats-new-april-2025.mdx

Fixes the OG image for the April what’s new blog post.

Fix blog post OG image

---

src/content/blog/solstice-festival.mdx

Adds link and updates entry for design contest.

add design contest info to solstice blog

---

src/content/blog/astro-db-deep-dive.mdx

I found a small typo in a command and I think it's worth fixing it alto this post is rather not one of the newest ones 😅

fix: astro db command in Deep Dive

---

src/content/blog/solstice-festival.mdx

Embeds all the videos in the solstice blog, and changes the wording to be about catching up on the content

Embed vids into solstice blog

---

src/content/blog/solstice-festival.mdx

https://github.com/withastro/astro.build/issues/1662
Update YouTube Channel link to correct channel with content. 
https://www.youtube.com/@AstroBuild --> https://www.youtube.com/@astrodotbuild

Update solstice-festival.mdx YouTube Channel Link

---

src/pages/_components/landing-page/Features.astro

Fix link to Actions documentation

---

src/content/blog/webflow-official-partner.mdx

Webflow blog post (actual)

---

src/content/blog/webflow-official-partner.mdx

- adds better semantic link text (taken from Webflow's FAQ
- ports over earlier suggestions from the preview branch to remove some redundancy ("In addition... also")

minor Webflow post polishes

---

src/content/blog/whats-new-september-2025.mdx

Removes what was supposed to be a "one time only" SUPER SHOWCASE extended version heading for August

September was not a SUPER showcase month!
